version: '1'

services:

  db-origin:
    image: psqlairflow-db-origin:latest
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-passwd
      POSTGRES_DB: postgres-db
    ports:
      - 7654:5432
    networks:
      - db-origin-net
    volumes: 
      - /var/lib/postgresql/origin

  db-dest:
    image: psqlairflow-db-dest:latest
    environment:
      POSTGRES_USER: other-postgres-user
      POSTGRES_PASSWORD: other-postgres-passwd
      POSTGRES_DB: other-postgres-db
    ports:
      - 6543:5432
    networks:
      - db-dest-net
    volumes: 
      - /var/lib/postgresql/dest

networks:
  db-origin-net: {}
  db-dest-net: {}