version: '3.8'

services:

  db-origin:
    image: psqlairflow-db-origin:latest
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-passwd
      POSTGRES_DB: postgres-db
    ports:
      - 5432:5432
    volumes: 
      - /var/lib/postgresql/origin

  db-dest:
    image: psqlairflow-db-dest:latest
    environment:
      POSTGRES_USER: other-postgres-user
      POSTGRES_PASSWORD: other-postgres-passwd
      POSTGRES_DB: other-postgres-db
    ports:
      - 6543:5432
    volumes: 
      - /var/lib/postgresql/dest